/**
 * The `/git-panel/*` route layer: the host half of the transport.
 *
 * It lives in `adapter/` rather than beside the git service because it is the
 * host's transport seam: `ctx.webServer` is named here and nowhere else in the
 * host half.
 *
 * ## Why HTTP routes and not a Typert Remote
 *
 * The doc prefers a Typert Remote (§5.3) and this plugin's ports were designed so
 * that choice could be revisited without touching the UI or the git logic. Two
 * facts decided it the other way for now:
 *
 * 1. A Remote method needs a wire schema generated by
 *    `@deepseek-ai/dsh-typert-generator` from the main repository's FaceModel.
 *    That generator is not published and not present in the installed DSH, so an
 *    out-of-tree plugin cannot produce the artifact by the supported route.
 *    `ctx.typert.register()` does accept hand-written schemas, but nothing in
 *    this deployment has proven that path for an external bundle.
 * 2. The mature out-of-tree git plugin already installed in this profile
 *    (`@linxin666/dsh-client-ui-git-graph`) does host-side git over exactly these
 *    `webServer` routes plus an SSE change stream, which is the doc's own
 *    fallback (§5.3: "备选方案是 webServer 路由").
 *
 * Because the browser half talks to {@link GitRemoteClient} and never to a URL,
 * swapping this file — and only this file — for a Typert Remote is the whole
 * migration.
 *
 * ## Shape
 *
 * Every JSON response is one envelope: `{ ok: true, value }` or
 * `{ ok: false, error }`. A failure is data, not an HTTP status, so the UI has
 * one code path and git's own multi-line output survives as `error.detail`.
 *
 * Reads answer `GET`, with the session in the query; mutations require `POST`,
 * with the session and their arguments in a JSON body. Two gates precede any git
 * work: the loopback fence below, and — for mutations only — a same-origin check,
 * because a state-changing route that any page on this machine can `POST` to is a
 * hole the loopback fence does not close by itself.
 *
 * @module dsh-git-panel/host/adapter/routes
 */

import type { IncomingMessage, ServerResponse } from 'node:http'
import type { Context } from '@deepseek-ai/cordis'
import type {} from '@deepseek-ai/dsh-host-webserver'
import type { GitPanelError, HostPorts, WorkspaceGitService } from '../../core/ports.ts'
import type { GitProbe } from '../git-probe.ts'

/** The path prefix this plugin owns; distinct from git-graph's `/git`. */
const ROUTE_PREFIX = '/git-panel'

/**
 * Operations that only read, and therefore answer `GET`.
 *
 * The two sets are what keeps the transport honest: a read can never be a
 * mutation, and a mutation can never arrive as a `GET` that a cross-site
 * `<img>` tag could trigger.
 */
const READ_OPERATIONS: ReadonlySet<string> = new Set([
  'status',
  'branches',
  'log',
  'diff',
  'showCommit',
])

/**
 * Operations that mutate the repository, and therefore require `POST`.
 *
 * `generateCommitMessage` is here although it changes nothing on disk: it spends
 * the deployment's model budget, which a cross-site `<img>` tag must not be able
 * to do, and `POST` plus the same-origin check is exactly that fence.
 */
const WRITE_OPERATIONS: ReadonlySet<string> = new Set([
  'stage',
  'unstage',
  'commit',
  'push',
  'pull',
  'sync',
  'checkout',
  'createBranch',
  'deleteBranch',
  'continueMerge',
  'abortMerge',
  'generateCommitMessage',
])

/**
 * Largest request body accepted, in bytes.
 *
 * §5.5 caps what the host SENDS; the same reasoning applies to what it reads. A
 * mutation body is a session id, a short message, and a list of paths, so a
 * megabyte is already far past anything legitimate.
 */
const MAX_BODY_BYTES = 1024 * 1024

/**
 * Whether a request arrived over the loopback interface.
 *
 * This fence exists because the DSH frontend's own authentication does NOT cover
 * routes a third-party plugin registers on `ctx.webServer`: `/` answers 401
 * without a session, while a plugin route answers normally. Verified against the
 * running server, and the reason the comparable external git plugin in this
 * profile carries its own loopback + paired-device gate.
 *
 * Loopback-only is the strictest useful default: a `dsh web` bound to
 * `127.0.0.1` (the default) is reachable by nothing else anyway, so this only
 * changes behaviour for a deployment that deliberately binds wider — and for
 * that deployment, refusing is better than silently exposing every session's
 * repository state to the network. A trusted-authority or paired-device escape
 * hatch belongs with the mutations in a later milestone, not before them.
 * @param req - The incoming request.
 * @returns Whether the peer is this machine.
 */
function isLoopback(req: IncomingMessage): boolean {
  const address = req.socket.remoteAddress
  if (address === undefined) return false
  if (address === '::1') return true
  // An IPv4 peer seen through an IPv6 socket arrives mapped.
  const ipv4 = address.startsWith('::ffff:') ? address.slice('::ffff:'.length) : address
  return /^127\./.test(ipv4)
}

/** How long an idle SSE connection is kept warm. */
const HEARTBEAT_MS = 15_000

/** One envelope every JSON response carries. */
type Envelope<T> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly error: GitPanelError }

/** JSON response headers. `no-store` keeps a stale panel out of any cache. */
const JSON_HEADERS = {
  'content-type': 'application/json; charset=utf-8',
  'cache-control': 'no-store',
  'referrer-policy': 'no-referrer',
} as const

/**
 * Write one JSON envelope.
 * @param res - Response to write.
 * @param status - HTTP status; always 200 for a well-formed request, since the
 *   envelope carries the failure.
 * @param body - The envelope.
 */
function writeJson(res: ServerResponse, status: number, body: Envelope<unknown>): void {
  res.writeHead(status, JSON_HEADERS)
  res.end(JSON.stringify(body))
}

/** Build a failure envelope. */
function fail(code: GitPanelError['code'], message: string): Envelope<never> {
  return { ok: false, error: { code, message } }
}

/**
 * Read the `session` query parameter.
 * @param url - The request URL, already parsed.
 * @returns The session id, or `null` when absent or empty.
 */
function sessionOf(url: URL): string | null {
  const value = url.searchParams.get('session')
  return value === null || value === '' ? null : value
}

/**
 * Where the session id came from, body first.
 *
 * Reads carry it in the query because they have no body; mutations carry it in
 * the body, which is where the rest of their arguments are. Accepting both keeps
 * one rule — "the session is required" — rather than one per method.
 * @param url - The request URL.
 * @param body - The parsed body, `{}` for a read.
 * @returns The session id, or `null` when neither place supplied one.
 */
function sessionFrom(url: URL, body: Record<string, unknown>): string | null {
  const fromBody = body['session']
  if (typeof fromBody === 'string' && fromBody !== '') return fromBody
  return sessionOf(url)
}

/**
 * Whether a mutating request came from this very origin.
 *
 * The loopback fence stops other machines; this stops other *pages*. A browser
 * attaches `Origin` to a `POST` it makes, and a cross-site page cannot forge it,
 * so a mismatch is a request the user did not make from this panel. A request
 * with no `Origin` at all is not a browser cross-site request — a test, a script,
 * the plugin's own tooling — and loopback is what guards those.
 * @param req - The incoming request.
 * @returns Whether the request may proceed.
 */
function isSameOrigin(req: IncomingMessage): boolean {
  const origin = req.headers.origin
  if (origin === undefined || origin === '') return true
  const host = req.headers.host
  if (host === undefined) return false
  try {
    return new URL(origin).host === host
  } catch {
    // An `Origin` that is not a URL cannot be this origin.
    return false
  }
}

/**
 * Read a bounded JSON request body.
 *
 * Bounded in bytes rather than trusted to `content-length`, because the header
 * is the client's claim and the stream is the fact.
 * @param req - The incoming request.
 * @returns The parsed object, or the failure to answer with.
 */
async function readJsonBody(req: IncomingMessage): Promise<Envelope<Record<string, unknown>>> {
  const chunks: Buffer[] = []
  let size = 0
  try {
    for await (const chunk of req) {
      const buffer = chunk as Buffer
      size += buffer.length
      if (size > MAX_BODY_BYTES) {
        return fail('too-large', 'the request body is too large')
      }
      chunks.push(buffer)
    }
  } catch {
    return fail('bad-request', 'the request body could not be read')
  }

  const text = Buffer.concat(chunks).toString('utf8')
  if (text.trim() === '') return { ok: true, value: {} }
  try {
    const parsed: unknown = JSON.parse(text)
    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
      return fail('bad-request', 'the request body must be a JSON object')
    }
    return { ok: true, value: parsed as Record<string, unknown> }
  } catch {
    return fail('bad-request', 'the request body is not valid JSON')
  }
}

/**
 * Read one field that must be an array of strings.
 *
 * The wire shape is checked here and the git shape in `core/validate.ts`: this
 * layer answers "is it an array of strings", the service answers "is it a path
 * this plugin may hand to git". That split keeps the pure rules in the pure
 * layer and this file's job to the transport.
 * @param body - The parsed body.
 * @param name - Field name.
 * @returns The array, or the envelope to answer with.
 */
function stringArrayOf(body: Record<string, unknown>, name: string): Envelope<readonly string[]> {
  const value = body[name]
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== 'string')) {
    return fail('bad-request', `${name} must be an array of strings`)
  }
  return { ok: true, value: value as readonly string[] }
}

/**
 * Read one field that must be a non-empty string.
 *
 * The wire shape is checked here and the git shape in `core/validate.ts`, the
 * same split {@link stringArrayOf} follows: this layer answers "is it a string",
 * the service answers "is it a branch name this plugin may hand to git".
 * @param body - The parsed body.
 * @param name - Field name.
 * @returns The string, or the envelope to answer with.
 */
function stringOf(body: Record<string, unknown>, name: string): Envelope<string> {
  const value = body[name]
  if (typeof value !== 'string' || value === '') {
    return fail('bad-request', `${name} must be a non-empty string`)
  }
  return { ok: true, value }
}

/**
 * Read a non-negative integer query parameter.
 * @param url - The request URL.
 * @param name - Parameter name.
 * @param fallback - Value to use when absent or unparseable.
 * @returns The parsed value, or the fallback.
 */
function intOf(url: URL, name: string, fallback: number): number {
  const raw = url.searchParams.get(name)
  if (raw === null) return fallback
  const value = Number(raw)
  return Number.isSafeInteger(value) && value >= 0 ? value : fallback
}

/**
 * Register the routes.
 *
 * Two registrations, because the SSE stream must NOT be swallowed by the JSON
 * handler: the JSON handler owns the `/git-panel` prefix and the stream owns the
 * exact path `/git-panel/events`, which the router resolves in favour of the
 * longer, exact match.
 * @param ctx - Host context carrying `webServer`.
 * @param service - The git service.
 * @param probe - The git state probe feeding the stream.
 * @param ports - Diagnostic port.
 * @returns A disposer that unregisters both routes and ends every open stream.
 */
export function registerGitPanelRoutes(
  ctx: Context,
  service: WorkspaceGitService,
  probe: GitProbe,
  ports: HostPorts,
): () => void {
  /** Live SSE responses, so disposal can end them rather than leak sockets. */
  const streams = new Set<ServerResponse>()

  /** Run one operation against the service. */
  async function dispatchOperation(
    operation: string,
    sessionId: string,
    url: URL,
    body: Record<string, unknown>,
  ): Promise<Envelope<unknown>> {
    switch (operation) {
      case 'status':
        return await service.status(sessionId)
      case 'branches':
        return await service.branches(sessionId)
      case 'log':
        return await service.log(sessionId, intOf(url, 'offset', 0), intOf(url, 'limit', 30))
      case 'diff': {
        const path = url.searchParams.get('path')
        if (path === null || path === '') {
          return fail('bad-request', 'the path query parameter is required')
        }
        const area = url.searchParams.get('area')
        // Checked here rather than passed through: the service's `DiffArea` is a
        // two-value union, and a third value arriving from the wire should be a
        // refusal the caller can read, not a type error nobody sees.
        if (area !== 'worktree' && area !== 'index') {
          return fail('bad-request', 'the area query parameter must be worktree or index')
        }
        return await service.diff(sessionId, path, area, intOf(url, 'context', 3))
      }
      case 'stage':
      case 'unstage': {
        const paths = stringArrayOf(body, 'paths')
        if (!paths.ok) return paths
        return operation === 'stage'
          ? await service.stage(sessionId, paths.value)
          : await service.unstage(sessionId, paths.value)
      }
      case 'commit': {
        const message = body['message']
        if (typeof message !== 'string') {
          return fail('bad-request', 'message must be a string')
        }
        // FR-3.4's two commits differ only in this flag: the panel sets it when
        // its button reads "commit all tracked changes", and the service then
        // does the `add -u` the label promised.
        return body['all'] === true
          ? await service.commitAll(sessionId, message)
          : await service.commit(sessionId, message)
      }
      case 'push':
        return await service.push(sessionId)
      case 'pull':
        return await service.pull(sessionId)
      case 'sync':
        return await service.sync(sessionId)
      case 'showCommit': {
        const hash = url.searchParams.get('hash')
        if (hash === null || hash === '') {
          return fail('bad-request', 'the hash query parameter is required')
        }
        return await service.showCommit(sessionId, hash)
      }
      case 'checkout': {
        const name = stringOf(body, 'name')
        if (!name.ok) return name
        return await service.checkout(sessionId, name.value)
      }
      case 'createBranch': {
        const name = stringOf(body, 'name')
        if (!name.ok) return name
        // An absent base means "from the current HEAD", which is FR-4.2's first
        // choice; a present one must be a string, so `base: 7` is refused here
        // rather than silently becoming the branch named "7".
        const rawBase = body['base']
        if (rawBase !== undefined && rawBase !== null && typeof rawBase !== 'string') {
          return fail('bad-request', 'base must be a string when it is given')
        }
        const base = typeof rawBase === 'string' && rawBase !== '' ? rawBase : null
        return await service.createBranch(sessionId, name.value, base)
      }
      case 'deleteBranch': {
        const name = stringOf(body, 'name')
        if (!name.ok) return name
        return await service.deleteBranch(sessionId, name.value, body['force'] === true)
      }
      case 'continueMerge':
        return await service.continueMerge(sessionId)
      case 'abortMerge':
        return await service.abortMerge(sessionId)
      case 'generateCommitMessage': {
        // The locale decides the message's language; an absent one falls back to
        // the panel's own default instead of being an error, since it only
        // affects the wording of the answer.
        const locale = typeof body['locale'] === 'string' ? body['locale'] : 'en'
        return await service.generateCommitMessage(sessionId, locale)
      }
      default:
        return fail('bad-request', `unknown operation: ${operation}`)
    }
  }

  /** Handle one JSON operation: reads answer GET, mutations require POST. */
  const handler = async (req: IncomingMessage, res: ServerResponse): Promise<void> => {
    if (!isLoopback(req)) {
      ports.log('warn', `refused ${ROUTE_PREFIX} request from ${req.socket.remoteAddress ?? 'unknown'}`)
      writeJson(res, 403, fail('bad-request', 'this endpoint accepts loopback clients only'))
      return
    }

    const url = new URL(req.url ?? '/', 'http://localhost')
    const operation = url.pathname.slice(ROUTE_PREFIX.length).replace(/^\/+/, '')
    const isWrite = WRITE_OPERATIONS.has(operation)
    if (!isWrite && !READ_OPERATIONS.has(operation)) {
      writeJson(res, 404, fail('bad-request', `unknown operation: ${operation}`))
      return
    }

    const method = req.method ?? ''
    if (isWrite ? method !== 'POST' : method !== 'GET') {
      writeJson(res, 405, fail('bad-request', `${method === '' ? 'that' : method} is not supported here`))
      return
    }

    // A mutation gets the check a read never needed: a cross-site page can make
    // the browser send a request, but it cannot make it claim this origin.
    if (isWrite && !isSameOrigin(req)) {
      ports.log(
        'warn',
        `refused a cross-origin ${operation} from ${req.headers.origin ?? 'an unknown origin'}`,
      )
      writeJson(res, 403, fail('bad-request', 'a mutation must come from this origin'))
      return
    }

    let body: Record<string, unknown> = {}
    if (isWrite) {
      const parsed = await readJsonBody(req)
      if (!parsed.ok) {
        writeJson(res, parsed.error.code === 'too-large' ? 413 : 400, parsed)
        return
      }
      body = parsed.value
    }

    const sessionId = sessionFrom(url, body)
    if (sessionId === null) {
      writeJson(res, 400, fail('bad-request', 'the session is required'))
      return
    }

    try {
      const result = await dispatchOperation(operation, sessionId, url, body)
      writeJson(res, 200, result.ok ? { ok: true, value: result.value } : result)
    } catch (error) {
      // A thrown handler must still answer, or the browser waits for a response
      // that will never come.
      ports.log('error', `route ${operation} threw: ${String(error)}`)
      writeJson(res, 500, fail('internal', error instanceof Error ? error.message : String(error)))
    }
  }

  /** Handle one SSE subscription. */
  const stream = async (req: IncomingMessage, res: ServerResponse): Promise<void> => {
    if (!isLoopback(req)) {
      ports.log('warn', `refused ${ROUTE_PREFIX}/events from ${req.socket.remoteAddress ?? 'unknown'}`)
      writeJson(res, 403, fail('bad-request', 'this endpoint accepts loopback clients only'))
      return
    }

    const url = new URL(req.url ?? '/', 'http://localhost')
    const sessionId = sessionOf(url)
    if (sessionId === null) {
      writeJson(res, 400, fail('bad-request', 'the session query parameter is required'))
      return
    }

    res.writeHead(200, {
      'content-type': 'text/event-stream; charset=utf-8',
      'cache-control': 'no-store',
      connection: 'keep-alive',
      // Proxies that buffer would defeat a stream whose whole point is latency.
      'x-accel-buffering': 'no',
    })
    // Tell the browser how fast to reconnect after a drop.
    res.write('retry: 2000\n\n')
    streams.add(res)

    // The stream is worthless without a repository to watch, and resolving the
    // root costs one git call; a failure is reported as an error frame so the
    // client can stop retrying and show the reason.
    const status = await service.status(sessionId)
    let unsubscribe: (() => void) | null = null
    if (status.ok) {
      // Subscribing BEFORE saying ready: the probe resolves only once it is
      // live, so a change made after this await is reported rather than
      // absorbed. The frame carries what moved, which is what lets a pane
      // re-read only what it shows.
      unsubscribe = await probe.watch(status.value.root, (change) => {
        res.write(`event: changed\ndata: ${JSON.stringify(change)}\n\n`)
      })
      // The client can vanish while the probe was starting; in that case
      // release immediately rather than holding a subscription nobody reads.
      if (res.writableEnded || res.destroyed) {
        unsubscribe()
        unsubscribe = null
      } else {
        res.write('event: ready\ndata: {}\n\n')
      }
    } else {
      res.write(`event: unavailable\ndata: ${JSON.stringify(status.error)}\n\n`)
    }

    const heartbeat = setInterval(() => {
      // A comment frame keeps intermediaries from closing an idle connection.
      res.write(': ping\n\n')
    }, HEARTBEAT_MS)
    heartbeat.unref()

    const cleanup = (): void => {
      clearInterval(heartbeat)
      unsubscribe?.()
      unsubscribe = null
      streams.delete(res)
    }
    res.on('close', cleanup)
    // A client that vanishes mid-write makes the response stream error; without
    // this listener that becomes an unhandled 'error' on the host process.
    res.on('error', cleanup)
  }

  const disposers = [
    ctx.webServer.register({ kind: 'prefix', path: ROUTE_PREFIX, handler }),
    ctx.webServer.register({ kind: 'exact', path: `${ROUTE_PREFIX}/events`, handler: stream }),
  ]

  return () => {
    for (const dispose of disposers) dispose()
    for (const res of streams) res.end()
    streams.clear()
  }
}
