/**
 * The `/git-panel/*` route layer: the host half of the transport.
 *
 * It lives in `adapter/` rather than beside the git service because it is the
 * host's transport seam: `ctx.webServer` is named here and nowhere else in the
 * host half.
 *
 * ## Why HTTP routes and not a Typert Remote
 *
 * The doc prefers a Typert Remote (§5.3) and this plugin's ports were designed so
 * that choice could be revisited without touching the UI or the git logic. Two
 * facts decided it the other way for now:
 *
 * 1. A Remote method needs a wire schema generated by
 *    `@deepseek-ai/dsh-typert-generator` from the main repository's FaceModel.
 *    That generator is not published and not present in the installed DSH, so an
 *    out-of-tree plugin cannot produce the artifact by the supported route.
 *    `ctx.typert.register()` does accept hand-written schemas, but nothing in
 *    this deployment has proven that path for an external bundle.
 * 2. The mature out-of-tree git plugin already installed in this profile
 *    (`@linxin666/dsh-client-ui-git-graph`) does host-side git over exactly these
 *    `webServer` routes plus an SSE change stream, which is the doc's own
 *    fallback (§5.3: "备选方案是 webServer 路由").
 *
 * Because the browser half talks to {@link GitRemoteClient} and never to a URL,
 * swapping this file — and only this file — for a Typert Remote is the whole
 * migration.
 *
 * ## Shape
 *
 * Every JSON response is one envelope: `{ ok: true, value }` or
 * `{ ok: false, error }`. A failure is data, not an HTTP status, so the UI has
 * one code path and git's own multi-line output survives as `error.detail`.
 *
 * @module dsh-git-panel/host/adapter/routes
 */

import type { IncomingMessage, ServerResponse } from 'node:http'
import type { Context } from '@deepseek-ai/cordis'
import type {} from '@deepseek-ai/dsh-host-webserver'
import type { GitPanelError, HostPorts, WorkspaceGitService } from '../../core/ports.ts'
import type { RepoWatcher } from '../watcher.ts'

/** The path prefix this plugin owns; distinct from git-graph's `/git`. */
const ROUTE_PREFIX = '/git-panel'

/**
 * Whether a request arrived over the loopback interface.
 *
 * This fence exists because the DSH frontend's own authentication does NOT cover
 * routes a third-party plugin registers on `ctx.webServer`: `/` answers 401
 * without a session, while a plugin route answers normally. Verified against the
 * running server, and the reason the comparable external git plugin in this
 * profile carries its own loopback + paired-device gate.
 *
 * Loopback-only is the strictest useful default: a `dsh web` bound to
 * `127.0.0.1` (the default) is reachable by nothing else anyway, so this only
 * changes behaviour for a deployment that deliberately binds wider — and for
 * that deployment, refusing is better than silently exposing every session's
 * repository state to the network. A trusted-authority or paired-device escape
 * hatch belongs with the mutations in a later milestone, not before them.
 * @param req - The incoming request.
 * @returns Whether the peer is this machine.
 */
function isLoopback(req: IncomingMessage): boolean {
  const address = req.socket.remoteAddress
  if (address === undefined) return false
  if (address === '::1') return true
  // An IPv4 peer seen through an IPv6 socket arrives mapped.
  const ipv4 = address.startsWith('::ffff:') ? address.slice('::ffff:'.length) : address
  return /^127\./.test(ipv4)
}

/** How long an idle SSE connection is kept warm. */
const HEARTBEAT_MS = 15_000

/** One envelope every JSON response carries. */
type Envelope<T> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly error: GitPanelError }

/** JSON response headers. `no-store` keeps a stale panel out of any cache. */
const JSON_HEADERS = {
  'content-type': 'application/json; charset=utf-8',
  'cache-control': 'no-store',
  'referrer-policy': 'no-referrer',
} as const

/**
 * Write one JSON envelope.
 * @param res - Response to write.
 * @param status - HTTP status; always 200 for a well-formed request, since the
 *   envelope carries the failure.
 * @param body - The envelope.
 */
function writeJson(res: ServerResponse, status: number, body: Envelope<unknown>): void {
  res.writeHead(status, JSON_HEADERS)
  res.end(JSON.stringify(body))
}

/** Build a failure envelope. */
function fail(code: GitPanelError['code'], message: string): Envelope<never> {
  return { ok: false, error: { code, message } }
}

/**
 * Read the `session` query parameter.
 * @param url - The request URL, already parsed.
 * @returns The session id, or `null` when absent or empty.
 */
function sessionOf(url: URL): string | null {
  const value = url.searchParams.get('session')
  return value === null || value === '' ? null : value
}

/**
 * Read a non-negative integer query parameter.
 * @param url - The request URL.
 * @param name - Parameter name.
 * @param fallback - Value to use when absent or unparseable.
 * @returns The parsed value, or the fallback.
 */
function intOf(url: URL, name: string, fallback: number): number {
  const raw = url.searchParams.get(name)
  if (raw === null) return fallback
  const value = Number(raw)
  return Number.isSafeInteger(value) && value >= 0 ? value : fallback
}

/**
 * Register the routes.
 *
 * Two registrations, because the SSE stream must NOT be swallowed by the JSON
 * handler: the JSON handler owns the `/git-panel` prefix and the stream owns the
 * exact path `/git-panel/events`, which the router resolves in favour of the
 * longer, exact match.
 * @param ctx - Host context carrying `webServer`.
 * @param service - The git service.
 * @param watcher - The change watcher feeding the stream.
 * @param ports - Diagnostic port.
 * @returns A disposer that unregisters both routes and ends every open stream.
 */
export function registerGitPanelRoutes(
  ctx: Context,
  service: WorkspaceGitService,
  watcher: RepoWatcher,
  ports: HostPorts,
): () => void {
  /** Live SSE responses, so disposal can end them rather than leak sockets. */
  const streams = new Set<ServerResponse>()

  /** Handle one JSON operation. */
  const handler = async (req: IncomingMessage, res: ServerResponse): Promise<void> => {
    if (!isLoopback(req)) {
      ports.log('warn', `refused ${ROUTE_PREFIX} request from ${req.socket.remoteAddress ?? 'unknown'}`)
      writeJson(res, 403, fail('bad-request', 'this endpoint accepts loopback clients only'))
      return
    }

    const url = new URL(req.url ?? '/', 'http://localhost')
    const operation = url.pathname.slice(ROUTE_PREFIX.length).replace(/^\/+/, '')

    if (req.method !== 'GET') {
      writeJson(res, 405, fail('bad-request', `${req.method ?? 'that'} is not supported`))
      return
    }

    const sessionId = sessionOf(url)
    if (sessionId === null) {
      writeJson(res, 400, fail('bad-request', 'the session query parameter is required'))
      return
    }

    try {
      switch (operation) {
        case 'status': {
          const result = await service.status(sessionId)
          writeJson(res, 200, result.ok ? { ok: true, value: result.value } : result)
          return
        }
        case 'branches': {
          const result = await service.branches(sessionId)
          writeJson(res, 200, result.ok ? { ok: true, value: result.value } : result)
          return
        }
        case 'log': {
          const result = await service.log(
            sessionId,
            intOf(url, 'offset', 0),
            intOf(url, 'limit', 30),
          )
          writeJson(res, 200, result.ok ? { ok: true, value: result.value } : result)
          return
        }
        default:
          writeJson(res, 404, fail('bad-request', `unknown operation: ${operation}`))
          return
      }
    } catch (error) {
      // A thrown handler must still answer, or the browser waits for a response
      // that will never come.
      ports.log('error', `route ${operation} threw: ${String(error)}`)
      writeJson(res, 500, fail('internal', error instanceof Error ? error.message : String(error)))
    }
  }

  /** Handle one SSE subscription. */
  const stream = async (req: IncomingMessage, res: ServerResponse): Promise<void> => {
    if (!isLoopback(req)) {
      ports.log('warn', `refused ${ROUTE_PREFIX}/events from ${req.socket.remoteAddress ?? 'unknown'}`)
      writeJson(res, 403, fail('bad-request', 'this endpoint accepts loopback clients only'))
      return
    }

    const url = new URL(req.url ?? '/', 'http://localhost')
    const sessionId = sessionOf(url)
    if (sessionId === null) {
      writeJson(res, 400, fail('bad-request', 'the session query parameter is required'))
      return
    }

    res.writeHead(200, {
      'content-type': 'text/event-stream; charset=utf-8',
      'cache-control': 'no-store',
      connection: 'keep-alive',
      // Proxies that buffer would defeat a stream whose whole point is latency.
      'x-accel-buffering': 'no',
    })
    // Tell the browser how fast to reconnect after a drop.
    res.write('retry: 2000\n\n')
    streams.add(res)

    // The stream is worthless without a repository to watch, and resolving the
    // root costs one git call; a failure is reported as an error frame so the
    // client can stop retrying and show the reason.
    const status = await service.status(sessionId)
    let unsubscribe: (() => void) | null = null
    if (status.ok) {
      // Await the baseline BEFORE saying ready: a client told "ready" must not be
      // able to make a change that the watcher silently absorbed instead of
      // reporting. The promise resolves as soon as the first stat pass lands.
      unsubscribe = await watcher.watch(status.value.root, () => {
        res.write('event: changed\ndata: {}\n\n')
      })
      // The client can vanish while the baseline was being read; in that case
      // release immediately rather than holding a subscription nobody reads.
      if (res.writableEnded || res.destroyed) {
        unsubscribe()
        unsubscribe = null
      } else {
        res.write('event: ready\ndata: {}\n\n')
      }
    } else {
      res.write(`event: unavailable\ndata: ${JSON.stringify(status.error)}\n\n`)
    }

    const heartbeat = setInterval(() => {
      // A comment frame keeps intermediaries from closing an idle connection.
      res.write(': ping\n\n')
    }, HEARTBEAT_MS)
    heartbeat.unref()

    const cleanup = (): void => {
      clearInterval(heartbeat)
      unsubscribe?.()
      unsubscribe = null
      streams.delete(res)
    }
    res.on('close', cleanup)
    // A client that vanishes mid-write makes the response stream error; without
    // this listener that becomes an unhandled 'error' on the host process.
    res.on('error', cleanup)
  }

  const disposers = [
    ctx.webServer.register({ kind: 'prefix', path: ROUTE_PREFIX, handler }),
    ctx.webServer.register({ kind: 'exact', path: `${ROUTE_PREFIX}/events`, handler: stream }),
  ]

  return () => {
    for (const dispose of disposers) dispose()
    for (const res of streams) res.end()
    streams.clear()
  }
}
